# Generated by Django 2.2.4 on 2019-08-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='preorder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_restaurants.PreOrder'),
        ),
    ]
