# Generated by Django 2.2.4 on 2019-08-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0002_auto_20190829_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='preorder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_restaurants.PreOrder'),
        ),
    ]
