# Generated by Django 2.2.4 on 2019-08-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0003_auto_20190829_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed')], default='planned', max_length=20),
        ),
    ]
