# Generated by Django 2.2.4 on 2019-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0004_preorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tables',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='new', max_length=20),
        ),
    ]
