# Generated by Django 2.2.4 on 2019-08-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0005_auto_20190829_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='date',
        ),
        migrations.AddField(
            model_name='preorder',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reserved',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
