# Generated by Django 2.2.4 on 2019-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_restaurants', '0006_auto_20190829_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserved',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
